name: Setup Godot Engine

description: 'GitHub Action to setup Godot Engine from official GitHub releases.'

inputs:
  repo:
    description: 'Repository to download Godot from (default: godotengine/godot)'
    default: 'godotengine/godot'
  version:
    description: 'Godot version (e.g. 4.4-stable)'
    required: true
  bin-path:
    description: 'Path for binaries to be installed to, relative to the current working directory of the action. This is the path that will be added to the system path.'
    default: 'godot-bin'
  download_editor:
    description: 'Download Godot Editor binary'
    default: 'true'
  download_template:
    description: 'Download Godot export templates'
    default: 'false'
  mono:
    description: 'Download Mono version (C# support)'
    default: 'false'

author: Apps In a Cup
branding:
  icon: 'terminal'
  color: 'blue'

runs:
  using: 'composite'
  steps:
    - name: Download Godot Editor
      shell: bash
      run: |
        GODOT_VERSION="${{ inputs.version }}"
        BIN_PATH="${{ inputs.bin-path }}"
        DOWNLOAD_EDITOR="${{ inputs.download_editor }}"
        MONO="${{ inputs.mono }}"

        if [ -d "$BIN_PATH" ]; then
          rm -rf "$BIN_PATH"
        fi
        mkdir -p "$BIN_PATH"

        if [[ "$DOWNLOAD_EDITOR" == "true" ]]; then
          # Detect OS using GitHub Actions runner.os
          if [ "${{ runner.os }}" == "Linux" ]; then
            GODOT_PLATFORM="linux.x86_64"
          elif [ "${{ runner.os }}" == "macOS" ]; then
            GODOT_PLATFORM="macos.universal"
          elif [ "${{ runner.os }}" == "Windows" ]; then
            GODOT_PLATFORM="win64.exe"
          else
            echo "Unknown OS: ${{ runner.os }}"; exit 1
          fi
          # Determine if mono build is needed
          if [[ "$MONO" == "true" ]]; then
            # Linux mono uses _ instead of . in platform
            if [ "$GODOT_PLATFORM" == "linux.x86_64" ]; then
              GODOT_EDITOR_NAME="Godot_v${GODOT_VERSION}_mono_linux_x86_64.zip"
            # Windows mono uses win64 (not win64.exe) in filename
            elif [ "$GODOT_PLATFORM" == "win64.exe" ]; then
              GODOT_EDITOR_NAME="Godot_v${GODOT_VERSION}_mono_win64.zip"
            else
              GODOT_EDITOR_NAME="Godot_v${GODOT_VERSION}_mono_${GODOT_PLATFORM}.zip"
            fi
          else
            GODOT_EDITOR_NAME="Godot_v${GODOT_VERSION}_${GODOT_PLATFORM}.zip"
          fi
          GODOT_RELEASE_URL="https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}/$GODOT_EDITOR_NAME"
          echo "Downloading $GODOT_RELEASE_URL"
          curl -L "$GODOT_RELEASE_URL" -o godot_editor.zip
          unzip -o godot_editor.zip -d "$BIN_PATH"
          chmod -R +x "$BIN_PATH"/*
          # Find the Godot binary depending on platform
          GODOT_BIN_PATH=""
          if [[ "$GODOT_PLATFORM" == macos* ]]; then
            GODOT_BIN_PATH=$(find "$BIN_PATH" -type f -path "*/Godot.app/Contents/MacOS/Godot" | head -n 1)
          elif [[ "$GODOT_PLATFORM" == win* ]]; then
            GODOT_BIN_PATH=$(find "$BIN_PATH" -type f -name "*_console.exe" | head -n 1)
            if [[ -z "$GODOT_BIN_PATH" ]]; then
              GODOT_BIN_PATH=$(find "$BIN_PATH" -type f -name "*.exe" | head -n 1)
            fi
          else
            GODOT_BIN_PATH=$(find "$BIN_PATH" -type f -executable -name "Godot*" | head -n 1)
          fi
          echo "GODOT4=$GODOT_BIN_PATH" >> $GITHUB_ENV
          echo "$(dirname $GODOT_BIN_PATH)" >> $GITHUB_PATH
        fi
    - name: Download and Setup Godot Templates
      shell: bash
      if: inputs.download_template == 'true'
      run: |
        GODOT_VERSION="${{ inputs.version }}"
        BIN_PATH="${{ inputs.bin-path }}"
        MONO="${{ inputs.mono }}"
        mkdir -p "$BIN_PATH/templates"
        # Detect OS using GitHub Actions runner.os
        if [ "${{ runner.os }}" == "Linux" ]; then
          PLATFORM="linux"
        elif [ "${{ runner.os }}" == "macOS" ]; then
          PLATFORM="macos"
        elif [ "${{ runner.os }}" == "Windows" ]; then
          PLATFORM="windows"
        else
          echo "Unknown OS: ${{ runner.os }}"; exit 1
        fi
        if [[ "$MONO" == "true" ]]; then
          GODOT_TEMPLATE_NAME="Godot_v${GODOT_VERSION}_mono_export_templates.tpz"
        else
          GODOT_TEMPLATE_NAME="Godot_v${GODOT_VERSION}_export_templates.tpz"
        fi
        GODOT_TEMPLATE_URL="https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}/$GODOT_TEMPLATE_NAME"
        echo "Downloading $GODOT_TEMPLATE_URL"
        curl -L "$GODOT_TEMPLATE_URL" -o "$BIN_PATH/templates/$GODOT_TEMPLATE_NAME"
        file=$(ls "$BIN_PATH/templates")
        version_dot=$(echo "$GODOT_VERSION" | sed 's/-/./')
        echo "Unzipping template"
        echo "Version dot: $version_dot"
        # Set export path based on platform
        if [[ "$PLATFORM" == "macos" ]]; then
          EXPORT_PATH="/Users/runner/Library/Application Support/Godot/export_templates/$version_dot"
        elif [[ "$PLATFORM" == "linux" ]]; then
          EXPORT_PATH="$HOME/.local/share/godot/export_templates/$version_dot"
        else
          EXPORT_PATH="$HOME/AppData/Roaming/Godot/export_templates/$version_dot"
        fi
        mkdir -p "$EXPORT_PATH"
        unzip -o "$BIN_PATH/templates/$file" -d "$EXPORT_PATH"
        # Move up all files from templates/ if present
        if [ -d "$EXPORT_PATH/templates" ]; then
          mv "$EXPORT_PATH/templates"/* "$EXPORT_PATH/"
          rmdir "$EXPORT_PATH/templates"
        fi
        ls "$EXPORT_PATH"
        echo "GODOT_TEMPLATE=$EXPORT_PATH" >> $GITHUB_ENV
